update

diff --git a/.github/workflows/daily-ete-test.yml b/.github/workflows/daily-ete-test.yml
--- a/.github/workflows/daily-ete-test.yml
+++ b/.github/workflows/daily-ete-test.yml
@@ -17,7 +17,7 @@ on:
         required: true
         description: 'regression types'
         type: string
-        default: "['infer', 'eval', 'cmd']"
+        default: "['infer', 'eval', 'cmd', 'cluster']"
       baseline_result:
         required: true
         description: 'baseline result'
@@ -215,7 +215,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        eval_func: ["chat_obj_fullbench_v5", "chat_obj_fullbench_v6", "chat_obj_fullbench_v7", "chat_obj_fullbench_v8", "eval_chat_obj_v8", "chat_obj_fullbench_other", "chat_sub_fullbench", "base_fullbench","base_longtext_fullbench","chat_longtext_fullbench"]
+        eval_func: ["chat_obj_fullbench_v5", "chat_obj_fullbench_v6", "chat_obj_fullbench_v7", "chat_obj_fullbench_v8", "chat_obj_v8", "chat_obj_fullbench_other", "chat_sub_fullbench", "base_fullbench","base_longtext_fullbench","chat_longtext_fullbench"]
     runs-on: yidian_cu12_daily
     timeout-minutes: 240 #4hours
     steps:
@@ -232,14 +232,14 @@ jobs:
           conda activate ${{env.CONDA_ENV}}
           conda info --envs
           pip list
-      - name: Run test - without judger
+      - name: Run test - without out judger
         if: matrix.eval_func == 'chat_obj_fullbench_v5' || matrix.eval_func == 'base_fullbench' || matrix.eval_func == 'base_longtext_fullbench' || matrix.eval_func == 'chat_longtext_fullbench'
         run: |
           . ${{env.CONDA_PATH}}/bin/activate
           conda activate ${{env.CONDA_ENV}}
 
           mkdir ${{env.REPORT_ROOT}}/${{ github.run_id }} -p 
-          cp -r ${{env.REPORT_ROOT}}/${{ env.BASELINE_DIR }}/eval_${{matrix.eval_func}} ${{env.REPORT_ROOT}}/${{ github.run_id }}/eval_${{matrix.eval_func}} 
+          cp -r ${{env.REPORT_ROOT}}/${{ env.BASELINE_DIR }}/predictions/eval_${{matrix.eval_func}} ${{env.REPORT_ROOT}}/${{ github.run_id }}/eval_${{matrix.eval_func}} 
 
           echo ${{github.workspace}}
           
@@ -260,14 +260,42 @@ jobs:
             fi
             sleep 6
           done
-      - name: Run test - with judger
-        if: matrix.eval_func != 'chat_obj_fullbench_v5' && matrix.eval_func != 'base_fullbench' && matrix.eval_func != 'base_longtext_fullbench' && matrix.eval_func != 'chat_longtext_fullbench'
+      - name: Run test - other subdatasets
+        if: matrix.eval_func == 'chat_sub_fullbench'
         run: |
           . ${{env.CONDA_PATH}}/bin/activate
           conda activate ${{env.CONDA_ENV}}
 
           mkdir ${{env.REPORT_ROOT}}/${{ github.run_id }} -p 
-          cp -r ${{env.REPORT_ROOT}}/${{ env.BASELINE_DIR }}/eval_${{matrix.eval_func}} ${{env.REPORT_ROOT}}/${{ github.run_id }}/eval_${{matrix.eval_func}} 
+          cp -r ${{env.REPORT_ROOT}}/${{ env.BASELINE_DIR }}/predictions/eval_${{matrix.eval_func}} ${{env.REPORT_ROOT}}/${{ github.run_id }}/eval_${{matrix.eval_func}} 
+
+          echo ${{github.workspace}}
+          
+          JOB_NAME=eval-${{ github.run_id }}-${{ matrix.eval_func }}-${{ github.run_attempt }}
+          JOB_NAME=${JOB_NAME//_/-}
+          
+          rjob submit --metadata-name=$JOB_NAME --charged-group=opencompass_gpu --private-machine=group --group=opencompass_gpu --gpu=1 --cpu=32 --memory=32568 --private-machine=group --image=registry.h.pjlab.org.cn/ailab-puyu/xpuyu:torch-2.6.0-45d96d5f-0607 --env=COMPASS_DATA_CACHE=/mnt/shared-storage-user/auto-eval-pipeline/opencompass/llmeval/compass_data_cache_sub --env=TIKTOKEN_CACHE_DIR=/mnt/shared-storage-user/auto-eval-pipeline/opencompass/llmeval/share_tiktoken --env=HF_ENDPOINT=https://hf-mirror.com --env=HF_DATASETS_CACHE=/mnt/shared-storage-user/opencompass-shared/qa-llm-cicd/hf_cache --env=HF_HUB_CACHE=/mnt/shared-storage-gpfs2/gpfs2-shared-public/huggingface/hub --env=CUDA_MODULE_LOADING=EAGER --env=HF_DATASETS_OFFLINE=1 --env=TRANSFORMERS_OFFLINE=1 --env=HF_EVALUATE_OFFLINE=1 --env=HF_HUB_OFFLINE=1 --env=VLLM_USE_MODELSCOPE=false --env=VLLM_WORKER_MULTIPROC_METHOD=spawn --mount=gpfs://gpfs1/qa-llm-cicd:/mnt/shared-storage-user/qa-llm-cicd --mount=gpfs://gpfs1/opencompass-shared:/mnt/shared-storage-user/opencompass-shared --mount=gpfs://gpfs1/auto-eval-pipeline:/mnt/shared-storage-user/auto-eval-pipeline --mount=gpfs://gpfs2/gpfs2-shared-public:/mnt/shared-storage-gpfs2/gpfs2-shared-public --host-network=True -- bash -exc 'source ${{env.CONDA_PATH}}/bin/activate; conda activate ${{env.CONDA_ENV}}; conda env list; cd ${{github.workspace}}; opencompass autotest/eval/eval_${{matrix.eval_func}}.py -m eval --work-dir ${{env.REPORT_ROOT}}/${{ github.run_id }}/eval_${{matrix.eval_func}} --reuse --dump-res-length'
+
+          for i in {1..300}; do
+            current_status=$(rjob get $JOB_NAME | grep -oP 'rjob [^:]+: \K[^ ]+')
+            if [[ $current_status == "Succeeded" ]]; then
+              echo "Task succeeded"
+              exit 0
+            elif [[ $current_status == "Failed" || $current_status == "Stopped" ]]; then
+              echo "Task failed or stopped, fetching logs"
+              rjob logs job $JOB_NAME
+              exit 1
+            fi
+            sleep 6
+          done
+      - name: Run test - with judger
+        if: matrix.eval_func != 'chat_obj_fullbench_v5' && matrix.eval_func != 'base_fullbench' && matrix.eval_func != 'base_longtext_fullbench' && matrix.eval_func != 'chat_longtext_fullbench' && matrix.eval_func != 'chat_sub_fullbench'
+        run: |
+          . ${{env.CONDA_PATH}}/bin/activate
+          conda activate ${{env.CONDA_ENV}}
+
+          mkdir ${{env.REPORT_ROOT}}/${{ github.run_id }} -p 
+          cp -r ${{env.REPORT_ROOT}}/${{ env.BASELINE_DIR }}/predictions/eval_${{matrix.eval_func}} ${{env.REPORT_ROOT}}/${{ github.run_id }}/eval_${{matrix.eval_func}} 
 
           echo ${{github.workspace}}
           
@@ -352,3 +380,39 @@ jobs:
           python -m pytest -m case4 -s -v --color=yes autotest/utils/oc_score_assert.py
           rm regression_result_daily -f && ln -s ${{env.REPORT_ROOT}}/${{ github.run_id }}/cmd5/*/summary regression_result_daily
           python -m pytest -m case5 -s -v --color=yes autotest/utils/oc_score_assert.py
+
+  daily_run_cluster:
+    if: ${{!cancelled() && contains(needs.prepare_env.result, 'success') && (github.event_name == 'schedule' || contains(fromJSON(github.event.inputs.regression_type), 'cluster'))}}
+    needs: prepare_env
+    runs-on: yidian_cu12_daily
+    timeout-minutes: 240 #4hours
+    steps:
+      - name: Clean workdir
+        run: sudo git clean -ffdx
+      - name: Clone repository
+        uses: actions/checkout@v5
+        with:
+          repository: ${{ github.event.inputs.repo_org || 'open-compass/opencompass' }}
+          ref: ${{github.event.inputs.repo_ref || 'main'}}
+      - name: conda env 
+        run: |
+          . ${{env.CONDA_PATH}}/bin/activate
+          conda activate ${{env.CONDA_ENV}}
+          conda info --envs
+          pip list
+      - name: change rjob.py
+        run: |
+          cp /mnt/shared-storage-user/opencompass-shared/qa-llm-cicd/config/rjob.py .
+          sed -i "s/TASK_ID='none'/TASK_ID='${{ github.run_id }}'/g" rjob.py
+      - name: Run test
+        run: |
+          . ${{env.CONDA_PATH}}/bin/activate
+          conda activate ${{env.CONDA_ENV}}
+          conda info --envs
+          opencompass autotest/cluster/chat_models.py --work-dir ${{env.REPORT_ROOT}}/${{ github.run_id }}/cluster --reuse --dump-res-length
+      - name: Assert result
+        run: |
+          . ${{env.CONDA_PATH}}/bin/activate
+          conda activate ${{env.CONDA_ENV}}
+          conda info --envs
+          python .github/scripts/compare_results.py compare_results ${{env.REPORT_ROOT}}/${{ github.run_id }}/cluster ${{env.REPORT_ROOT}}/${{env.BASELINE_DIR}}/cluster
